# Python env   : Python v3.12.0
# -*- coding: utf-8 -*-
# @Time    : 2025/4/14 上午10:44
# @Author  : 李清水
# @File    : editor.py
# @Description : WS2812像素矩阵编辑器GUI工具，支持可视化编辑和JSON配置导入导出
# @License : MIT

# ======================================== 导入相关模块 =========================================

import tkinter as tk
from tkinter import colorchooser, filedialog, messagebox, simpledialog
import json

# ======================================== 全局变量 ============================================

# ======================================== 功能函数 ============================================

def rgb565_to_rgb888(rgb565):
    """
    高精度RGB565转RGB888（使用硬件级优化算法，提升转换精度）
    :param rgb565: RGB565格式的颜色值（16位整数）
    :return: 转换后的RGB888格式颜色元组（r, g, b），每个分量为0-255的整数；若出错则无返回（弹出错误提示）
    """
    try:
        r = (rgb565 >> 11) & 0x1F
        g = (rgb565 >> 5) & 0x3F
        b = rgb565 & 0x1F
        return (
            (r * 527 + 23) >> 6,
            (g * 259 + 33) >> 6,
            (b * 527 + 23) >> 6
        )
    except Exception as e:
        messagebox.showerror("转换错误", f"RGB565转RGB888时发生错误: {e}")

def rgb888_to_rgb565(r, g, b):
    """
    符合嵌入式系统标准的RGB888转RGB565（含自动溢出保护，确保输入在有效范围）
    :param r: RGB888的红色分量（整数，理论上可为任意值，函数会自动限制在0-255）
    :param g: RGB888的绿色分量（整数，理论上可为任意值，函数会自动限制在0-255）
    :param b: RGB888的蓝色分量（整数，理论上可为任意值，函数会自动限制在0-255）
    :return: 转换后的RGB565格式颜色值（16位整数）；若出错则无返回（弹出错误提示）
    """
    try:
        r = min(max(r, 0), 255)
        g = min(max(g, 0), 255)
        b = min(max(b, 0), 255)
        return ((r >> 3) << 11) | ((g >> 2) << 5) | (b >> 3)
    except Exception as e:
        messagebox.showerror("转换错误", f"RGB888转RGB565时发生错误: {e}")

def rgb_to_hex(rgb_tuple):
    """
    将RGB888元组转换为十六进制颜色代码（符合CSS/UI设计的标准格式）
    :param rgb_tuple: RGB888格式的颜色元组，包含r、g、b三个分量（每个分量为0-255的整数）
    :return: 十六进制颜色代码字符串（格式为#rrggbb，如#ffffff表示白色）；若出错则无返回（弹出错误提示）
    """
    try:
        return "#{:02x}{:02x}{:02x}".format(*rgb_tuple)
    except Exception as e:
        messagebox.showerror("转换错误", f"RGB转十六进制时发生错误: {e}")

# ======================================== 自定义类 ============================================

class PixelEditor:
    """
    WS2812点阵像素编辑器类，支持像素绘制、颜色选择、JSON文件导入/导出、撤销操作等功能
    核心特性：
        1. 支持自定义点阵尺寸，自动适配像素显示大小
        2. 支持鼠标点击/拖拽绘制像素
        3. 支持JSON格式的点阵数据加载与保存
        4. 提供撤销功能，支持颜色选择器
    """
    def __init__(self, parent_container, json_file=None):
        """
        初始化像素编辑器的界面和数据
        :param parent_container: 父容器（可以是tk.Frame、tk.Tk或tk.Toplevel对象）
        :param json_file: 可选参数，要加载的JSON点阵数据文件路径（字符串），默认为None
        :return: 无返回值
        """
        # 添加窗口类型判断
        if isinstance(parent_container, tk.Toplevel):
            self.root = tk.Frame(parent_container)
            self.root.pack(expand=True, fill="both")
        else:
            self.root = parent_container

        # 初始化撤销栈、像素大小参数和矩形ID存储
        # 存储像素数据的历史状态，用于撤销操作
        self.undo_stack = []
        # 默认单个像素的显示尺寸（像素）
        self.default_pixel_size = 30
        # 当前单个像素的显示尺寸
        self.pixel_size = self.default_pixel_size
        # 当前绘制使用的颜色（RGB888）
        self.current_color = (255, 255, 255)
        # 存储每个像素的矩形ID
        self.rect_ids = []

        # 默认模板
        self.data_template = {
            "pixels": [], # 存储RGB565格式的点阵颜色数据
            "width": 8, # 点阵宽度（列数）
            "height": 8, # 点阵高度（行数）
            "description": "Generated by WS2812 Driver System", # 点阵描述信息
            "version": 1.2 # 数据版本号
        }

        # 创建UI组件
        self.create_widgets()

        # 加载JSON文件或初始化默认模板
        if json_file:
            self.load_json(json_file)
        else:
            self.initialize_default()

        self.draw_pixels()

    def initialize_default(self):
        """
        生成默认测试图案（前4列红色，后4列绿色的8×8点阵）
        :return: 无返回值
        """
        self.data = self.data_template.copy()
        # 构造默认像素数据：每行前4个像素为红色，后4个为绿色
        self.data["pixels"] = [
            rgb888_to_rgb565(255, 0, 0) if x < 4 else rgb888_to_rgb565(0, 255, 0)
            for _ in range(8) for x in range(8)
        ]

    def new_template(self):
        """
        新建纯白模板，支持用户自定义点阵尺寸并自动适配像素显示大小
            1. 弹出输入框让用户输入宽度和高度（限制宽度≤256，高度≤128）
            2. 根据屏幕尺寸计算合适的像素显示大小
            3. 初始化纯白点阵数据并重新绘制
        :return: 无返回值
        """
        try:
            # 将编辑器窗口提升到顶层
            self.root.lift()
            # 弹出输入框获取宽度（最小值1，最大值256）
            w = simpledialog.askinteger("宽度", "请输入模板宽度:", parent=self.root, minvalue=1, maxvalue=256)
            # 用户取消输入
            if w is None: return
            # 弹出输入框获取高度（最小值1，最大值128）
            h = simpledialog.askinteger("高度", "请输入模板高度:", parent=self.root, minvalue=1, maxvalue=128)
            if h is None: return

            # 尺寸超限提示
            if w > 256 or h > 128:
                messagebox.showwarning("尺寸超限", "宽度<=256，高度<=128", parent=self.root)
                return

            # 计算最大可显示的像素尺寸（基于屏幕尺寸的2/3）
            max_w = (self.root.winfo_screenwidth() * 2) // 3
            max_h = (self.root.winfo_screenheight() * 2) // 3
            cell_w = max_w // w
            cell_h = max_h // h

            # 限制像素尺寸在5到默认尺寸之间
            self.pixel_size = max(5, min(self.default_pixel_size, cell_w, cell_h))

            # 初始化纯白点阵数据
            white = rgb888_to_rgb565(255, 255, 255)
            self.data = {"pixels": [white] * (w * h), "width": w, "height": h,
                         "description": "Pure white template", "version": 1.0}
            # 清空撤销栈
            self.undo_stack.clear()
            # 调整画布尺寸并重新绘制像素
            self.canvas.config(width=w * self.pixel_size, height=h * self.pixel_size)
            # 更新状态提示
            self.draw_pixels()
            self.status_label.config(text=f"已创建 {w}×{h} 模板")
        except Exception as e:
            messagebox.showerror("新建错误", f"错误: {e}")

    def create_widgets(self):
        """
        创建编辑器的UI组件，包括画布、控制按钮、颜色预览框、状态标签
            1. 创建画布用于显示和绘制像素
            2. 创建控制按钮（新建模板、选择颜色、导入/导出JSON、撤销）
            3. 创建颜色预览标签和状态提示标签
        :return: 无返回值
        """
        try:
            # 创建画布（背景色为深灰色）
            self.canvas = tk.Canvas(self.root, bg="#404040")
            self.canvas.pack(padx=5, pady=5, expand=True, fill=tk.BOTH)
            # 绑定鼠标事件：左键点击绘制像素、左键拖拽绘制像素
            self.canvas.bind("<Button-1>", self.on_pixel_click)
            self.canvas.bind("<B1-Motion>", self.on_pixel_drag)

            # 创建控制按钮框架
            ctrl = tk.Frame(self.root)
            ctrl.pack(pady=5)
            # 创建颜色预览标签
            self.color_preview = tk.Label(ctrl, width=6, height=2, bg=rgb_to_hex(self.current_color))
            self.color_preview.pack(side=tk.LEFT, padx=5)
            # 创建功能按钮：新建模板、选择颜色、导入JSON、保存JSON、撤销
            for txt, cmd in [("新建模板", self.new_template),
                             ("选择颜色", self.choose_color),
                             ("导入JSON", self.load_file),
                             ("保存JSON", self.save_file),
                             ("撤销", self.undo)]:
                tk.Button(ctrl, text=txt, width=8, command=cmd).pack(side=tk.LEFT, padx=5)

            # 创建状态提示标签（下沉样式，左对齐）
            self.status_label = tk.Label(self.root, text="欢迎！", bd=1, relief=tk.SUNKEN, anchor=tk.W)
            self.status_label.pack(side=tk.BOTTOM, fill=tk.X)
        except Exception as e:
            messagebox.showerror("UI错误", str(e))

    def draw_pixels(self):
        """
        初始化或重绘整个像素矩阵，根据self.data中的点阵数据在画布上绘制矩形像素
            1. 清空画布所有内容
            2. 遍历每个像素位置，计算矩形坐标并绘制
            3. 存储每个矩形的ID到self.rect_ids，用于后续颜色更新
        :return: 无返回值
        """
        # 清空画布
        self.canvas.delete("all")
        self.rect_ids = []

        # 获取点阵的宽度和高度
        w, h = self.data["width"], self.data["height"]
        for y in range(h):
            row = []
            for x in range(w):
                idx = y * w + x
                color = rgb565_to_rgb888(self.data["pixels"][idx])
                hexc = rgb_to_hex(color)
                x0, y0 = x * self.pixel_size, y * self.pixel_size
                rid = self.canvas.create_rectangle(x0, y0, x0 + self.pixel_size,
                                                   y0 + self.pixel_size,
                                                   fill=hexc, outline="gray")
                row.append(rid)
            self.rect_ids.append(row)

    def on_pixel_click(self, event):
        """
        处理鼠标左键点击事件：在点击位置绘制当前颜色的像素，并记录历史状态到撤销栈
        :param event: 鼠标事件对象（包含点击的x、y坐标）
        :return: 无返回值
        """
        try:
            # 计算点击位置对应的像素坐标（x列，y行）
            x, y = event.x // self.pixel_size, event.y // self.pixel_size
            # 检查坐标是否在点阵范围内
            if 0 <= x < self.data["width"] and 0 <= y < self.data["height"]:
                self.undo_stack.append(self.data["pixels"][:])
                idx = y * self.data["width"] + x
                self.data["pixels"][idx] = rgb888_to_rgb565(*self.current_color)
                hexc = rgb_to_hex(rgb565_to_rgb888(self.data["pixels"][idx]))
                self.canvas.itemconfig(self.rect_ids[y][x], fill=hexc)
        except Exception as e:
            messagebox.showerror("点击错误", str(e))

    def on_pixel_drag(self, event):
        """
        处理鼠标左键拖拽事件：在拖拽路径上绘制当前颜色的像素
        :param event: 鼠标事件对象（包含拖拽的x、y坐标）
        :return: 无返回值
        """
        try:
            # 计算拖拽位置对应的像素坐标（x列，y行）
            x, y = event.x // self.pixel_size, event.y // self.pixel_size
            if 0 <= x < self.data["width"] and 0 <= y < self.data["height"]:
                idx = y * self.data["width"] + x
                self.data["pixels"][idx] = rgb888_to_rgb565(*self.current_color)
                hexc = rgb_to_hex(rgb565_to_rgb888(self.data["pixels"][idx]))
                self.canvas.itemconfig(self.rect_ids[y][x], fill=hexc)
        except Exception as e:
            messagebox.showerror("拖拽错误", str(e))

    def choose_color(self):
        """
        打开系统颜色选择器，让用户选择绘制颜色，并更新颜色预览标签
        :return: 无返回值
        """
        try:
            clr = colorchooser.askcolor(parent=self.root)
            if clr[0]:
                self.current_color = tuple(map(int, clr[0]))
                self.color_preview.config(bg=rgb_to_hex(self.current_color))
        except Exception as e:
            messagebox.showerror("颜色错误", str(e))

    def load_json(self, path):
        """
        加载并验证JSON点阵数据文件，根据点阵尺寸自动适配像素显示大小
        :param path: JSON文件的路径（字符串）
        :return: 无返回值
        """
        try:
            with open(path) as f:
                d = json.load(f)
            for k in ("pixels", "width", "height"): assert k in d
            self.data = d
            # 根据新尺寸重新计算像素格大小
            w, h = d["width"], d["height"]
            max_w = (self.root.winfo_screenwidth() * 2) // 3
            max_h = (self.root.winfo_screenheight() * 2) // 3
            cell_w = max_w // w
            cell_h = max_h // h
            self.pixel_size = max(5, min(self.default_pixel_size, cell_w, cell_h))
            self.canvas.config(width=w * self.pixel_size,
                               height=h * self.pixel_size)
            self.undo_stack.clear()
            self.draw_pixels()
            self.status_label.config(text="加载成功！")
        except Exception as e:
            messagebox.showerror("加载错误", str(e))

    def load_file(self):
        """
        打开文件选择对话框，让用户选择要导入的JSON文件，并调用load_json加载数据
        :return: 无返回值
        """
        try:
            # 获取编辑器窗口的顶层窗口
            parent_window = self.root.winfo_toplevel()
            fp = filedialog.askopenfilename(
                parent=parent_window,  # 关键修改：指定父窗口
                defaultextension=".json",
                filetypes=[("JSON", "*.json")]
            )
            if fp:
                self.load_json(fp)
        except Exception as e:
            messagebox.showerror("文件错误", str(e), parent=parent_window)

    def save_file(self):
        """
        打开保存文件对话框，让用户选择保存路径，将点阵数据保存为JSON文件
        :return: 无返回值
        """
        try:
            parent_window = self.root.winfo_toplevel()
            fp = filedialog.asksaveasfilename(
                parent=parent_window,  # 关键修改：指定父窗口
                defaultextension=".json",
                filetypes=[("JSON", "*.json")]
            )
            if fp:
                with open(fp, 'w') as f:
                    json.dump(self.data, f, indent=4)
                messagebox.showinfo("保存成功", "已保存", parent=parent_window)
        except Exception as e:
            messagebox.showerror("保存错误", str(e), parent=parent_window)

    def undo(self):
        """
        执行撤销操作：恢复到上一次的像素数据状态，并重新绘制像素
        仅当撤销栈不为空时生效
        :return: 无返回值
        """
        if self.undo_stack:
            self.data["pixels"] = self.undo_stack.pop()
            self.draw_pixels()

    def center_window(self, w, h):
        """
        将编辑器窗口居中显示在屏幕上
        :param w: 窗口宽度（像素）
        :param h: 窗口高度（像素）
        :return: 无返回值
        """
        sw, sh = self.root.winfo_screenwidth(), self.root.winfo_screenheight()
        x, y = (sw - w) // 2, (sh - h) // 2
        self.root.geometry(f"{w}x{h}+{x}+{y}")

# ======================================== 初始化配置 ==========================================

# ========================================  主程序  ===========================================

if __name__ == "__main__":
    # 示例用法
    root = tk.Tk()

    # 方式2：加载已有配置
    editor = PixelEditor(root, "G:/NeopixelMatrixTool/out/color_test.json")

    root.mainloop()